### ISSUE TITLE
VMware Workstation 17

### ISSUE THREAD

**Issue by Spectroxx** [ektajarwal1610/vmware-workstation16-pro-license-keys#3]
VMware Workstation 17 has been released
[Release Notes](https://docs.vmware.com/en/VMware-Workstation-Pro/17.0/rn/vmware-workstation-170-pro-release-notes/index.html)
[Workstation Pro 17 Windows Download](https://download3.vmware.com/software/WKST-1700-WIN/VMware-workstation-full-17.0.0-20800274.exe)
[Workstation Player 17 Windows Download](https://download3.vmware.com/software/WKST-PLAYER-1700/VMware-player-full-17.0.0-20800274.exe)

New keys are required.

**Comment by ghost** [comment]
What's new keys?
